# Generated by Django 4.2.7 on 2023-11-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_book_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="document",
            field=models.FileField(
                default="default.txt", null=True, upload_to="documents/"
            ),
        ),
    ]
